[package]
name = "diru"
version = "0.1.0"
edition = "2021"

[lib]

[[bin]]
name = "diru"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
